---
# tasks file for arillso.motd

- name: 'Debian : configure motd'
  become: true
  template:
    src: '{{ item }}.j2'
    dest: '/etc/update-motd.d/{{ item }}'
    owner: root
    group: root
    mode: '755'
  with_items:
    - 00-header
    - 01-welcome
    - 02-facts
    - 03-sysinfo
  tags:
    - configuration

- name: 'Debian : configure ascii-logo'
  become: true
  copy:
    content: '{{ motd_ascii_art }}'
    dest: '/etc/default/motd-ascii_art'
    owner: root
    group: root
    mode: '755'
  tags:
    - configuration

- name: 'Debian : remove motd'
  become: true
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/update-motd.d/10-uname'
    - '/etc/motd'
